doctrine_migrations:
    #dir_name: '%kernel.project_dir%/src/Migrations'
    dir_name: '%kernel.project_dir%/src/Infrastructure/Share/Migrations'    
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
