#twig:
#    default_path: '%kernel.project_dir%/templates'
#    debug: '%kernel.debug%'
#    strict_variables: '%kernel.debug%'

twig:
    paths: ['%kernel.project_dir%/src/UI/Http/Web/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'